### ISSUE TITLE
Possibly better alternative?

### ISSUE THREAD

**Issue by elreydetoda** [diodonfrost/ansible-role-vagrant#2]
##### SUMMARY

Use @hashicorp's packaging method, instead of querying for latest version: https://medium.com/hashicorp-engineering/hashicorp-packaging-is-here-4c6083dee4f6

##### ADDITIONAL INFORMATION

So, currently I believe the way you are pulling the vagrant packaging is still considered to be the "official" mechanism for installing vagrant, because they say to not use it in production, but I would imagine that eventually @hashicorp will move to using their repos as a more "official" way of pulling down their tools in the future.  So, instead of having to query `index.json` (which is really cool by the way I didn't know that existed!!! :grin:) you can just add the repos and then install all their tools by their name: `apt install vagrant` (since I am on a debian based system)

here is their gist for adding it: https://gist.github.com/jboero/c6c90c47837a2db0f6ac9095f6c733d0#file-hashicorprepo-sh

so, something like this:

```yaml
- name: add hashicorp apt signing key
  apt_key:
    url: 'https://apt.releases.hashicorp.com/gpg'
    state: present
- name: setup hashicorp apt repository on Ubuntu
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    state: present
- name: installing vagrant
  package:
    name: vagrant
    state: present
```
